# create a dataset

In [3]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Set random seed for reproducibility
np.random.seed(42)

# Generate 5000 transactions
n_rows = 5000

# Date range: Jan 2023 to Apr 2024
start_date = datetime(2023, 1, 1)
dates = [start_date + timedelta(days=np.random.randint(0, 485)) for _ in range(n_rows)]

# Create dataset
data = {
    'transaction_id': range(1, n_rows + 1),
    'order_date': dates,
    'customer_id': np.random.randint(1001, 1501, n_rows),
    'product_id': np.random.randint(1, 101, n_rows),
    'product_name': np.random.choice(['Laptop', 'Phone', 'Tablet', 'Headphones', 'Charger', 
                                       'Mouse', 'Keyboard', 'Monitor', 'Webcam', 'Speaker'], n_rows),
    'category': np.random.choice(['Electronics', 'Accessories', 'Computing'], n_rows),
    'quantity': np.random.randint(1, 11, n_rows),
    'unit_price': np.random.uniform(10, 1500, n_rows).round(2),
    'discount_pct': np.random.choice([0, 5, 10, 15, 20, 25], n_rows),
    'shipping_cost': np.random.choice([0, 5.99, 9.99, 15.99], n_rows),
    'payment_method': np.random.choice(['Credit Card', 'Debit Card', 'PayPal', 'Cash'], n_rows),
    'region': np.random.choice(['North', 'South', 'East', 'West'], n_rows),
    'store_id': np.random.randint(101, 111, n_rows),
    'is_returned': np.random.choice([0, 1], n_rows, p=[0.92, 0.08]),
    'customer_rating': np.random.choice([1, 2, 3, 4, 5, np.nan], n_rows, p=[0.02, 0.03, 0.10, 0.35, 0.45, 0.05])
}

df = pd.DataFrame(data)

# Add some intentional missing values
df.loc[np.random.choice(df.index, 100, replace=False), 'unit_price'] = np.nan
df.loc[np.random.choice(df.index, 80, replace=False), 'discount_pct'] = np.nan

# Save to CSV
df.to_csv('ecommerce_sales.csv', index=False)

print("Dataset created successfully!")
print(f"Shape: {df.shape}")
print(df.head())

Dataset created successfully!
Shape: (5000, 15)
   transaction_id order_date  customer_id  product_id product_name  \
0               1 2023-04-13         1467          12       Laptop
1               2 2024-03-11         1211           4        Mouse
2               3 2023-12-15         1140          95       Webcam
3               4 2023-09-28         1293          18       Tablet
4               5 2023-04-17         1298          80     Keyboard

      category  quantity  unit_price  discount_pct  shipping_cost  \
0  Accessories         3      595.41           0.0           5.99
1  Accessories         6      754.54           5.0           5.99
2  Electronics         3      797.49          25.0           5.99
3    Computing         8     1040.93          25.0           5.99
4  Accessories         5     1069.70          15.0          15.99

  payment_method region  store_id  is_returned  customer_rating
0     Debit Card   West       106            1              4.0
1         PayPal  North       106            0              4.0
2         PayPal   West       104            0              5.0
3           Cash  South       105            0              5.0
4     Debit Card  North       103            0              5.0

# LEVEL 1: EASY (Q1-8) - BASIC OPERATIONS

In [4]:
    # Q1: Load and Explore
    # Load the CSV and display:
    df=pd.read_csv('ecommerce_sales.csv')
    # First 10 rows
    df.head(10)

,transaction_id,order_date,customer_id,product_id,product_name,category,quantity,unit_price,discount_pct,shipping_cost,payment_method,region,store_id,is_returned,customer_rating
0,1,2023-04-13,1467,12,Laptop,Accessories,3,595.41,0.0,5.99,Debit Card,West,106,1,4.0
1,2,2024-03-11,1211,4,Mouse,Accessories,6,754.54,5.0,5.99,PayPal,North,106,0,4.0
2,3,2023-12-15,1140,95,Webcam,Electronics,3,797.49,25.0,5.99,PayPal,West,104,0,5.0
3,4,2023-09-28,1293,18,Tablet,Computing,8,1040.93,25.0,5.99,Cash,South,105,0,5.0
4,5,2023-04-17,1298,80,Keyboard,Accessories,5,1069.70,15.0,15.99,Debit Card,North,103,0,5.0
5,6,2023-03-13,1401,36,Mouse,Accessories,4,572.67,10.0,5.99,Cash,East,103,0,5.0
6,7,2023-07-08,1101,25,Monitor,Electronics,9,626.18,20.0,15.99,Debit Card,South,109,0,4.0
7,8,2023-01-21,1304,87,Tablet,Electronics,5,566.81,15.0,0.00,Debit Card,West,105,0,4.0
8,9,2023-04-13,1359,76,Tablet,Electronics,4,809.44,0.0,9.99,Credit Card,North,101,0,4.0
9,10,2023-05-02,1028,98,Headphones,Electronics,8,685.50,20.0,15.99,Credit Card,East,109,0,4.0

In [5]:
# Dataset shape (rows, columns)
df.shape

(5000, 15)

In [6]:
# Column names and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   transaction_id   5000 non-null   int64
 1   order_date       5000 non-null   object
 2   customer_id      5000 non-null   int64
 3   product_id       5000 non-null   int64
 4   product_name     5000 non-null   object
 5   category         5000 non-null   object
 6   quantity         5000 non-null   int64
 7   unit_price       4900 non-null   float64
 8   discount_pct     4920 non-null   float64
 9   shipping_cost    5000 non-null   float64
 10  payment_method   5000 non-null   object
 11  region           5000 non-null   object
 12  store_id         5000 non-null   int64
 13  is_returned      5000 non-null   int64
 14  customer_rating  4768 non-null   float64
dtypes: float64(4), int64(6), object(5)
memory usage: 586.1+ KB

In [62]:
# Summary statistics
df.describe()

,transaction_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,shipping_cost,store_id,is_returned,customer_rating,revenue,discount_amount,net_revenue,total_cost
count,5000.000000,5000,5000.000000,5000.000000,5000.000000,4900.000000,4920.000000,5000.000000,5000.000000,5000.000000,5000.000000,4900.000000,4820.000000,4820.000000,4820.000000
mean,2500.500000,2023-09-01 07:22:04.800000,1249.990400,51.184400,5.446000,769.904904,12.672764,8.064846,105.514600,0.084000,4.274400,4249.083712,541.593443,3714.171607,3722.217594
min,1.000000,2023-01-01 00:00:00,1001.000000,1.000000,1.000000,10.070000,0.000000,0.000000,101.000000,0.000000,1.000000,13.100000,0.000000,11.722500,11.790000
25%,1250.750000,2023-05-04 00:00:00,1124.750000,26.000000,3.000000,400.082500,5.000000,5.990000,103.000000,0.000000,4.000000,1342.855000,63.926625,1163.865000,1172.813250
50%,2500.500000,2023-09-02 00:00:00,1248.000000,52.000000,5.000000,777.445000,15.000000,9.990000,106.000000,0.000000,4.000000,3284.995000,295.578750,2847.845000,2855.835000
75%,3750.250000,2024-01-03 00:00:00,1376.000000,76.000000,8.000000,1141.855000,20.000000,15.990000,108.000000,0.000000,5.000000,6301.815000,780.821250,5553.258750,5561.693750
max,5000.000000,2024-04-29 00:00:00,1500.000000,100.000000,10.000000,1499.850000,25.000000,15.990000,110.000000,1.000000,5.000000,14942.700000,3672.650000,14861.800000,14877.790000
std,1443.520003,NaN,144.034687,28.767814,2.862014,430.058878,8.518580,5.826669,2.862696,0.277416,0.908884,3521.102406,650.403352,3114.584818,3114.663529

In [8]:
# Q2: Missing Values

# Count missing values in each column
df.isnull().sum()

transaction_id       0
order_date           0
customer_id          0
product_id           0
product_name         0
category             0
quantity             0
unit_price         100
discount_pct        80
shipping_cost        0
payment_method       0
region               0
store_id             0
is_returned          0
customer_rating    232
dtype: int64

In [9]:
# Calculate percentage of missing values
df.isnull().sum()/len(df) * 100

transaction_id     0.00
order_date         0.00
customer_id        0.00
product_id         0.00
product_name       0.00
category           0.00
quantity           0.00
unit_price         2.00
discount_pct       1.60
shipping_cost      0.00
payment_method     0.00
region             0.00
store_id           0.00
is_returned        0.00
customer_rating    4.64
dtype: float64

In [10]:
len(df)

5000

In [11]:
# Fill missing unit_price with median
df['unit_price'].fillna({'unit_price':df['unit_price'].median(),'inplace':True})

C:\Users\prave\AppData\Local\Temp\ipykernel_32212\500497073.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['unit_price'].fillna({'unit_price':df['unit_price'].median(),'inplace':True})

0        595.41
1        754.54
2        797.49
3       1040.93
4       1069.70
         ...
4995     274.68
4996     801.64
4997      74.95
4998     753.78
4999     196.93
Name: unit_price, Length: 5000, dtype: float64

In [12]:
# Fill missing discount_pct with 0
df['discount_pct'].fillna({'discount_pct':0,'inplace':True})

C:\Users\prave\AppData\Local\Temp\ipykernel_32212\1866030850.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['discount_pct'].fillna({'discount_pct':0,'inplace':True})

0        0.0
1        5.0
2       25.0
3       25.0
4       15.0
        ...
4995    25.0
4996    15.0
4997    25.0
4998     0.0
4999     5.0
Name: discount_pct, Length: 5000, dtype: float64

In [13]:
df.isnull().sum()

transaction_id       0
order_date           0
customer_id          0
product_id           0
product_name         0
category             0
quantity             0
unit_price         100
discount_pct        80
shipping_cost        0
payment_method       0
region               0
store_id             0
is_returned          0
customer_rating    232
dtype: int64

In [14]:
df.head(20)

,transaction_id,order_date,customer_id,product_id,product_name,category,quantity,unit_price,discount_pct,shipping_cost,payment_method,region,store_id,is_returned,customer_rating
0,1,2023-04-13,1467,12,Laptop,Accessories,3,595.41,0.0,5.99,Debit Card,West,106,1,4.0
1,2,2024-03-11,1211,4,Mouse,Accessories,6,754.54,5.0,5.99,PayPal,North,106,0,4.0
2,3,2023-12-15,1140,95,Webcam,Electronics,3,797.49,25.0,5.99,PayPal,West,104,0,5.0
3,4,2023-09-28,1293,18,Tablet,Computing,8,1040.93,25.0,5.99,Cash,South,105,0,5.0
4,5,2023-04-17,1298,80,Keyboard,Accessories,5,1069.70,15.0,15.99,Debit Card,North,103,0,5.0
5,6,2023-03-13,1401,36,Mouse,Accessories,4,572.67,10.0,5.99,Cash,East,103,0,5.0
6,7,2023-07-08,1101,25,Monitor,Electronics,9,626.18,20.0,15.99,Debit Card,South,109,0,4.0
7,8,2023-01-21,1304,87,Tablet,Electronics,5,566.81,15.0,0.00,Debit Card,West,105,0,4.0
8,9,2023-04-13,1359,76,Tablet,Electronics,4,809.44,0.0,9.99,Credit Card,North,101,0,4.0
9,10,2023-05-02,1028,98,Headphones,Electronics,8,685.50,20.0,15.99,Credit Card,East,109,0,4.0
10,11,2024-04-11,1041,36,Tablet,Accessories,8,1335.50,5.0,9.99,PayPal,West,110,0,5.0
11,12,2023-08-03,1355,67,Webcam,Computing,8,1047.58,15.0,9.99,Debit Card,South,106,0,5.0
12,13,2023-11-27,1303,9,Headphones,Computing,4,NaN,20.0,9.99,PayPal,East,109,0,4.0
13,14,2024-04-03,1496,61,Mouse,Electronics,1,1066.61,15.0,15.99,Cash,South,107,0,5.0
14,15,2023-03-29,1146,53,Monitor,Electronics,2,1456.78,5.0,15.99,PayPal,North,110,0,4.0
15,16,2024-01-08,1256,18,Monitor,Accessories,4,957.25,25.0,15.99,Cash,East,110,0,3.0
16,17,2023-04-10,1462,43,Charger,Electronics,10,1445.69,15.0,0.00,Credit Card,North,107,0,4.0
17,18,2023-12-26,1227,35,Charger,Computing,2,245.67,0.0,15.99,Credit Card,West,105,0,5.0
18,19,2023-06-01,1236,63,Mouse,Electronics,10,88.19,20.0,0.00,Cash,West,107,1,4.0
19,20,2023-05-11,1361,98,Speaker,Computing,3,872.90,20.0,15.99,Cash,South,110,0,5.0

In [15]:
# Fill missing customer_rating with mode
df['customer_rating'] = df['customer_rating'].fillna(df['customer_rating'].mode()[0])

In [16]:
df.isnull().sum()

transaction_id       0
order_date           0
customer_id          0
product_id           0
product_name         0
category             0
quantity             0
unit_price         100
discount_pct        80
shipping_cost        0
payment_method       0
region               0
store_id             0
is_returned          0
customer_rating      0
dtype: int64

In [17]:
# Q3: Basic Calculations
# Create new columns:

# revenue = quantity × unit_price
df['revenue']=df['quantity']*df['unit_price']

In [18]:
# discount_amount = revenue × (discount_pct / 100)
df['discount_amount']=df['revenue']*(df['discount_pct']/100)

In [19]:
# net_revenue = revenue - discount_amount
df['net_revenue']=df['revenue']-df['discount_amount']

In [20]:
# total_cost = net_revenue + shipping_cost
df['total_cost']=df['net_revenue']+df['shipping_cost']

In [21]:
df.columns

Index(['transaction_id', 'order_date', 'customer_id', 'product_id',
       'product_name', 'category', 'quantity', 'unit_price', 'discount_pct',
       'shipping_cost', 'payment_method', 'region', 'store_id', 'is_returned',
       'customer_rating', 'revenue', 'discount_amount', 'net_revenue',
       'total_cost'],
      dtype='object')

In [22]:
df.head(3)

,transaction_id,order_date,customer_id,product_id,product_name,category,quantity,unit_price,discount_pct,shipping_cost,payment_method,region,store_id,is_returned,customer_rating,revenue,discount_amount,net_revenue,total_cost
0,1,2023-04-13,1467,12,Laptop,Accessories,3,595.41,0.0,5.99,Debit Card,West,106,1,4.0,1786.23,0.0000,1786.2300,1792.2200
1,2,2024-03-11,1211,4,Mouse,Accessories,6,754.54,5.0,5.99,PayPal,North,106,0,4.0,4527.24,226.3620,4300.8780,4306.8680
2,3,2023-12-15,1140,95,Webcam,Electronics,3,797.49,25.0,5.99,PayPal,West,104,0,5.0,2392.47,598.1175,1794.3525,1800.3425

In [23]:
df.describe()

,transaction_id,customer_id,product_id,quantity,unit_price,discount_pct,shipping_cost,store_id,is_returned,customer_rating,revenue,discount_amount,net_revenue,total_cost
count,5000.000000,5000.000000,5000.000000,5000.000000,4900.000000,4920.000000,5000.000000,5000.000000,5000.000000,5000.000000,4900.000000,4820.000000,4820.000000,4820.000000
mean,2500.500000,1249.990400,51.184400,5.446000,769.904904,12.672764,8.064846,105.514600,0.084000,4.274400,4249.083712,541.593443,3714.171607,3722.217594
std,1443.520003,144.034687,28.767814,2.862014,430.058878,8.518580,5.826669,2.862696,0.277416,0.908884,3521.102406,650.403352,3114.584818,3114.663529
min,1.000000,1001.000000,1.000000,1.000000,10.070000,0.000000,0.000000,101.000000,0.000000,1.000000,13.100000,0.000000,11.722500,11.790000
25%,1250.750000,1124.750000,26.000000,3.000000,400.082500,5.000000,5.990000,103.000000,0.000000,4.000000,1342.855000,63.926625,1163.865000,1172.813250
50%,2500.500000,1248.000000,52.000000,5.000000,777.445000,15.000000,9.990000,106.000000,0.000000,4.000000,3284.995000,295.578750,2847.845000,2855.835000
75%,3750.250000,1376.000000,76.000000,8.000000,1141.855000,20.000000,15.990000,108.000000,0.000000,5.000000,6301.815000,780.821250,5553.258750,5561.693750
max,5000.000000,1500.000000,100.000000,10.000000,1499.850000,25.000000,15.990000,110.000000,1.000000,5.000000,14942.700000,3672.650000,14861.800000,14877.790000

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   transaction_id   5000 non-null   int64
 1   order_date       5000 non-null   object
 2   customer_id      5000 non-null   int64
 3   product_id       5000 non-null   int64
 4   product_name     5000 non-null   object
 5   category         5000 non-null   object
 6   quantity         5000 non-null   int64
 7   unit_price       4900 non-null   float64
 8   discount_pct     4920 non-null   float64
 9   shipping_cost    5000 non-null   float64
 10  payment_method   5000 non-null   object
 11  region           5000 non-null   object
 12  store_id         5000 non-null   int64
 13  is_returned      5000 non-null   int64
 14  customer_rating  5000 non-null   float64
 15  revenue          4900 non-null   float64
 16  discount_amount  4820 non-null   float64
 17  net_revenue      4820 non-null   float64
 18  total_cost       4820 non-null   float64
dtypes: float64(8), int64(6), object(5)
memory usage: 742.3+ KB

In [25]:
# Q4: Filtering
# Filter the data to show:

# All orders where revenue > $500
df[df['revenue']>500]
# Orders from 'North' region with quantity > 5
df[(df['region']=='North') & (df['quantity']>5)]
# Transactions paid via 'Credit Card' OR 'PayPal'
df[(df['payment_method']=='Credit Card') | (df['payment_method']=='PayPal')]
# Orders that were NOT returned
df[df['is_returned']==0]

,transaction_id,order_date,customer_id,product_id,product_name,category,quantity,unit_price,discount_pct,shipping_cost,payment_method,region,store_id,is_returned,customer_rating,revenue,discount_amount,net_revenue,total_cost
1,2,2024-03-11,1211,4,Mouse,Accessories,6,754.54,5.0,5.99,PayPal,North,106,0,4.0,4527.24,226.3620,4300.8780,4306.8680
2,3,2023-12-15,1140,95,Webcam,Electronics,3,797.49,25.0,5.99,PayPal,West,104,0,5.0,2392.47,598.1175,1794.3525,1800.3425
3,4,2023-09-28,1293,18,Tablet,Computing,8,1040.93,25.0,5.99,Cash,South,105,0,5.0,8327.44,2081.8600,6245.5800,6251.5700
4,5,2023-04-17,1298,80,Keyboard,Accessories,5,1069.70,15.0,15.99,Debit Card,North,103,0,5.0,5348.50,802.2750,4546.2250,4562.2150
5,6,2023-03-13,1401,36,Mouse,Accessories,4,572.67,10.0,5.99,Cash,East,103,0,5.0,2290.68,229.0680,2061.6120,2067.6020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,2023-10-08,1221,77,Tablet,Accessories,1,274.68,25.0,9.99,Cash,North,110,0,3.0,274.68,68.6700,206.0100,216.0000
4996,4997,2023-04-04,1083,45,Mouse,Accessories,9,801.64,15.0,0.00,Cash,East,103,0,4.0,7214.76,1082.2140,6132.5460,6132.5460
4997,4998,2023-07-20,1182,88,Laptop,Computing,9,74.95,25.0,0.00,Credit Card,East,105,0,5.0,674.55,168.6375,505.9125,505.9125
4998,4999,2023-01-21,1307,87,Charger,Electronics,6,753.78,0.0,9.99,Credit Card,North,109,0,5.0,4522.68,0.0000,4522.6800,4532.6700
4999,5000,2023-12-06,1010,12,Keyboard,Accessories,7,196.93,5.0,9.99,Credit Card,East,110,0,5.0,1378.51,68.9255,1309.5845,1319.5745

In [26]:
# Q5: Sorting

# Sort by net_revenue in descending order
df['net_revenue'].sort_values(ascending=False)
# Show top 20 highest revenue transactions
df['net_revenue'].nlargest(10)
# Sort by order_date (oldest first), then by net_revenue (highest first)
df['order_date']=pd.to_datetime(df['order_date'])
df.sort_values(by=['order_date','net_revenue'],ascending=[True,False]).tail(5)

,transaction_id,order_date,customer_id,product_id,product_name,category,quantity,unit_price,discount_pct,shipping_cost,payment_method,region,store_id,is_returned,customer_rating,revenue,discount_amount,net_revenue,total_cost
1438,1439,2024-04-29,1204,37,Speaker,Accessories,3,194.62,5.0,0.00,Cash,West,108,0,5.0,583.86,29.1930,554.6670,554.6670
3284,3285,2024-04-29,1350,1,Headphones,Computing,1,310.29,10.0,0.00,PayPal,North,105,0,4.0,310.29,31.0290,279.2610,279.2610
277,278,2024-04-29,1050,32,Speaker,Electronics,3,58.97,20.0,9.99,PayPal,North,105,0,5.0,176.91,35.3820,141.5280,151.5180
2656,2657,2024-04-29,1319,58,Phone,Accessories,3,18.57,5.0,5.99,Debit Card,East,107,0,5.0,55.71,2.7855,52.9245,58.9145
193,194,2024-04-29,1059,70,Laptop,Electronics,4,400.52,NaN,9.99,PayPal,West,108,1,3.0,1602.08,NaN,NaN,NaN

In [27]:
df['order_date'].max()

Timestamp('2024-04-29 00:00:00')

In [28]:
df['order_date'].min()

Timestamp('2023-01-01 00:00:00')

In [29]:
# Q6: Unique Values
# Find:

# Number of unique customers
df['customer_id'].nunique()
# List of unique product names
df['product_name'].unique()
# Count of unique stores
df['store_id'].value_counts().sort_index()
# Most common payment method
df['payment_method'].value_counts().idxmax()

'Cash'

In [31]:
# Q7: Date Operations
# Extract from order_date:

# Year
df['order_date'].dt.year
# Month
df['order_date'].dt.month
# Day of week (0=Monday)
df['order_date'].dt.weekday
# Quarter
df['order_date'].dt.quarter
# Is it a weekend? (Saturday/Sunday)
df[(df['order_date'].dt.weekday==5) | (df['order_date'].dt.weekday==6)]

,transaction_id,order_date,customer_id,product_id,product_name,category,quantity,unit_price,discount_pct,shipping_cost,payment_method,region,store_id,is_returned,customer_rating,revenue,discount_amount,net_revenue,total_cost
6,7,2023-07-08,1101,25,Monitor,Electronics,9,626.18,20.0,15.99,Debit Card,South,109,0,4.0,5635.62,1127.1240,4508.4960,4524.4860
7,8,2023-01-21,1304,87,Tablet,Electronics,5,566.81,15.0,0.00,Debit Card,West,105,0,4.0,2834.05,425.1075,2408.9425,2408.9425
21,22,2023-11-05,1455,4,Speaker,Electronics,9,632.23,15.0,9.99,PayPal,North,106,0,5.0,5690.07,853.5105,4836.5595,4846.5495
23,24,2023-12-10,1013,41,Headphones,Accessories,7,787.10,15.0,9.99,Debit Card,West,110,0,5.0,5509.70,826.4550,4683.2450,4693.2350
24,25,2024-02-18,1210,45,Mouse,Accessories,4,976.71,15.0,15.99,Cash,North,103,0,5.0,3906.84,586.0260,3320.8140,3336.8040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4981,4982,2023-06-24,1071,57,Monitor,Computing,2,35.95,10.0,15.99,PayPal,West,107,0,5.0,71.90,7.1900,64.7100,80.7000
4990,4991,2023-12-30,1377,24,Headphones,Computing,4,1398.65,25.0,9.99,PayPal,West,109,0,5.0,5594.60,1398.6500,4195.9500,4205.9400
4992,4993,2023-09-30,1166,39,Webcam,Electronics,9,1028.55,20.0,15.99,Credit Card,East,102,0,4.0,9256.95,1851.3900,7405.5600,7421.5500
4995,4996,2023-10-08,1221,77,Tablet,Accessories,1,274.68,25.0,9.99,Cash,North,110,0,3.0,274.68,68.6700,206.0100,216.0000
4998,4999,2023-01-21,1307,87,Charger,Electronics,6,753.78,0.0,9.99,Credit Card,North,109,0,5.0,4522.68,0.0000,4522.6800,4532.6700

In [33]:
df['order_date'].dt.day_name()

0        Thursday
1          Monday
2          Friday
3        Thursday
4          Monday
          ...
4995       Sunday
4996      Tuesday
4997     Thursday
4998     Saturday
4999    Wednesday
Name: order_date, Length: 5000, dtype: object

In [54]:
# Q8: String Operations

# Convert all product_name to uppercase
df['product_name'].str.upper()
# Create a new column payment_type that shows "Card" if payment_method contains "Card", else "Other"
df['payment_type']=df['payment_method'].apply(lambda x: 'Card' if x =='Debit Card' or x=='Credit Card' else 'Other')
# Filter products whose name contains the letter 'o' (case insensitive)
df[df['product_name'].str.contains('o')]

,transaction_id,order_date,customer_id,product_id,product_name,category,quantity,unit_price,discount_pct,shipping_cost,payment_method,region,store_id,is_returned,customer_rating,revenue,discount_amount,net_revenue,total_cost,payment_type
0,1,2023-04-13,1467,12,Laptop,Accessories,3,595.41,0.0,5.99,Debit Card,West,106,1,4.0,1786.23,0.0000,1786.2300,1792.2200,Card
1,2,2024-03-11,1211,4,Mouse,Accessories,6,754.54,5.0,5.99,PayPal,North,106,0,4.0,4527.24,226.3620,4300.8780,4306.8680,Other
4,5,2023-04-17,1298,80,Keyboard,Accessories,5,1069.70,15.0,15.99,Debit Card,North,103,0,5.0,5348.50,802.2750,4546.2250,4562.2150,Card
5,6,2023-03-13,1401,36,Mouse,Accessories,4,572.67,10.0,5.99,Cash,East,103,0,5.0,2290.68,229.0680,2061.6120,2067.6020,Other
6,7,2023-07-08,1101,25,Monitor,Electronics,9,626.18,20.0,15.99,Debit Card,South,109,0,4.0,5635.62,1127.1240,4508.4960,4524.4860,Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4991,4992,2023-01-11,1143,99,Laptop,Accessories,10,71.35,15.0,5.99,PayPal,East,102,1,4.0,713.50,107.0250,606.4750,612.4650,Other
4994,4995,2024-03-06,1261,18,Headphones,Computing,7,1439.27,20.0,15.99,PayPal,East,109,0,5.0,10074.89,2014.9780,8059.9120,8075.9020,Other
4996,4997,2023-04-04,1083,45,Mouse,Accessories,9,801.64,15.0,0.00,Cash,East,103,0,4.0,7214.76,1082.2140,6132.5460,6132.5460,Other
4997,4998,2023-07-20,1182,88,Laptop,Computing,9,74.95,25.0,0.00,Credit Card,East,105,0,5.0,674.55,168.6375,505.9125,505.9125,Card
4999,5000,2023-12-06,1010,12,Keyboard,Accessories,7,196.93,5.0,9.99,Credit Card,East,110,0,5.0,1378.51,68.9255,1309.5845,1319.5745,Card

# LEVEL 2: MEDIUM (Q9-16) - GROUPING & AGGREGATION

In [50]:
df.columns

Index(['transaction_id', 'order_date', 'customer_id', 'product_id',
       'product_name', 'category', 'quantity', 'unit_price', 'discount_pct',
       'shipping_cost', 'payment_method', 'region', 'store_id', 'is_returned',
       'customer_rating', 'revenue', 'discount_amount', 'net_revenue',
       'total_cost', 'payment_type'],
      dtype='object')

In [59]:
# Q9: Simple GroupBy
# Calculate:

# Total revenue per category
df.groupby('category')['revenue'].sum()
# Average unit price per product
df.groupby('product_name')['unit_price'].mean()
# Number of transactions per region
df.groupby('region')['transaction_id'].count()
# Total quantity sold per store
df.groupby('store_id')['quantity'].sum()

store_id
101    2785
102    2601
103    2737
104    2825
105    2653
106    2668
107    2828
108    2806
109    2555
110    2772
Name: quantity, dtype: int64

In [71]:
# Q10: Multiple Aggregations
# For each category, calculate:
df.head(10)
# Total revenue
# df.groupby('category')['revenue'].sum()
# # Average revenue
# df.groupby('category')['revenue'].mean()
# # Number of transactions
# df.groupby('category')['transaction_id'].count()
# # Standard deviation of revenue
# df.groupby('category')['revenue'].sum()
# Min and max revenue

,transaction_id,order_date,customer_id,product_id,product_name,category,quantity,unit_price,discount_pct,shipping_cost,payment_method,region,store_id,is_returned,customer_rating,revenue,discount_amount,net_revenue,total_cost,payment_type
0,1,2023-04-13,1467,12,Laptop,Accessories,3,595.41,0.0,5.99,Debit Card,West,106,1,4.0,1786.23,0.0000,1786.2300,1792.2200,Card
1,2,2024-03-11,1211,4,Mouse,Accessories,6,754.54,5.0,5.99,PayPal,North,106,0,4.0,4527.24,226.3620,4300.8780,4306.8680,Other
2,3,2023-12-15,1140,95,Webcam,Electronics,3,797.49,25.0,5.99,PayPal,West,104,0,5.0,2392.47,598.1175,1794.3525,1800.3425,Other
3,4,2023-09-28,1293,18,Tablet,Computing,8,1040.93,25.0,5.99,Cash,South,105,0,5.0,8327.44,2081.8600,6245.5800,6251.5700,Other
4,5,2023-04-17,1298,80,Keyboard,Accessories,5,1069.70,15.0,15.99,Debit Card,North,103,0,5.0,5348.50,802.2750,4546.2250,4562.2150,Card
5,6,2023-03-13,1401,36,Mouse,Accessories,4,572.67,10.0,5.99,Cash,East,103,0,5.0,2290.68,229.0680,2061.6120,2067.6020,Other
6,7,2023-07-08,1101,25,Monitor,Electronics,9,626.18,20.0,15.99,Debit Card,South,109,0,4.0,5635.62,1127.1240,4508.4960,4524.4860,Card
7,8,2023-01-21,1304,87,Tablet,Electronics,5,566.81,15.0,0.00,Debit Card,West,105,0,4.0,2834.05,425.1075,2408.9425,2408.9425,Card
8,9,2023-04-13,1359,76,Tablet,Electronics,4,809.44,0.0,9.99,Credit Card,North,101,0,4.0,3237.76,0.0000,3237.7600,3247.7500,Card
9,10,2023-05-02,1028,98,Headphones,Electronics,8,685.50,20.0,15.99,Credit Card,East,109,0,4.0,5484.00,1096.8000,4387.2000,4403.1900,Card