# create a dataset

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Set random seed for reproducibility
np.random.seed(42)

# Generate 5000 transactions
n_rows = 5000

# Date range: Jan 2023 to Apr 2024
start_date = datetime(2023, 1, 1)
dates = [start_date + timedelta(days=np.random.randint(0, 485)) for _ in range(n_rows)]

# Create dataset
data = {
    'transaction_id': range(1, n_rows + 1),
    'order_date': dates,
    'customer_id': np.random.randint(1001, 1501, n_rows),
    'product_id': np.random.randint(1, 101, n_rows),
    'product_name': np.random.choice(['Laptop', 'Phone', 'Tablet', 'Headphones', 'Charger', 
                                       'Mouse', 'Keyboard', 'Monitor', 'Webcam', 'Speaker'], n_rows),
    'category': np.random.choice(['Electronics', 'Accessories', 'Computing'], n_rows),
    'quantity': np.random.randint(1, 11, n_rows),
    'unit_price': np.random.uniform(10, 1500, n_rows).round(2),
    'discount_pct': np.random.choice([0, 5, 10, 15, 20, 25], n_rows),
    'shipping_cost': np.random.choice([0, 5.99, 9.99, 15.99], n_rows),
    'payment_method': np.random.choice(['Credit Card', 'Debit Card', 'PayPal', 'Cash'], n_rows),
    'region': np.random.choice(['North', 'South', 'East', 'West'], n_rows),
    'store_id': np.random.randint(101, 111, n_rows),
    'is_returned': np.random.choice([0, 1], n_rows, p=[0.92, 0.08]),
    'customer_rating': np.random.choice([1, 2, 3, 4, 5, np.nan], n_rows, p=[0.02, 0.03, 0.10, 0.35, 0.45, 0.05])
}

df = pd.DataFrame(data)

# Add some intentional missing values
df.loc[np.random.choice(df.index, 100, replace=False), 'unit_price'] = np.nan
df.loc[np.random.choice(df.index, 80, replace=False), 'discount_pct'] = np.nan

# Save to CSV
df.to_csv('ecommerce_sales.csv', index=False)

print("Dataset created successfully!")
print(f"Shape: {df.shape}")
print(df.head())

Dataset created successfully!
Shape: (5000, 15)
   transaction_id order_date  customer_id  product_id product_name  \
0               1 2023-04-13         1467          12       Laptop
1               2 2024-03-11         1211           4        Mouse
2               3 2023-12-15         1140          95       Webcam
3               4 2023-09-28         1293          18       Tablet
4               5 2023-04-17         1298          80     Keyboard

      category  quantity  unit_price  discount_pct  shipping_cost  \
0  Accessories         3      595.41           0.0           5.99
1  Accessories         6      754.54           5.0           5.99
2  Electronics         3      797.49          25.0           5.99
3    Computing         8     1040.93          25.0           5.99
4  Accessories         5     1069.70          15.0          15.99

  payment_method region  store_id  is_returned  customer_rating
0     Debit Card   West       106            1              4.0
1         PayPal  North       106            0              4.0
2         PayPal   West       104            0              5.0
3           Cash  South       105            0              5.0
4     Debit Card  North       103            0              5.0

# LEVEL 1: EASY (Q1-8) - BASIC OPERATIONS

In [21]:
# Q1: Load and Explore
# Load the CSV and display:
df=pd.read_csv('ecommerce_sales.csv')
# First 10 rows
df.head(10)

,transaction_id,order_date,customer_id,product_id,product_name,category,quantity,unit_price,discount_pct,shipping_cost,payment_method,region,store_id,is_returned,customer_rating
0,1,2023-04-13,1467,12,Laptop,Accessories,3,595.41,0.0,5.99,Debit Card,West,106,1,4.0
1,2,2024-03-11,1211,4,Mouse,Accessories,6,754.54,5.0,5.99,PayPal,North,106,0,4.0
2,3,2023-12-15,1140,95,Webcam,Electronics,3,797.49,25.0,5.99,PayPal,West,104,0,5.0
3,4,2023-09-28,1293,18,Tablet,Computing,8,1040.93,25.0,5.99,Cash,South,105,0,5.0
4,5,2023-04-17,1298,80,Keyboard,Accessories,5,1069.70,15.0,15.99,Debit Card,North,103,0,5.0
5,6,2023-03-13,1401,36,Mouse,Accessories,4,572.67,10.0,5.99,Cash,East,103,0,5.0
6,7,2023-07-08,1101,25,Monitor,Electronics,9,626.18,20.0,15.99,Debit Card,South,109,0,4.0
7,8,2023-01-21,1304,87,Tablet,Electronics,5,566.81,15.0,0.00,Debit Card,West,105,0,4.0
8,9,2023-04-13,1359,76,Tablet,Electronics,4,809.44,0.0,9.99,Credit Card,North,101,0,4.0
9,10,2023-05-02,1028,98,Headphones,Electronics,8,685.50,20.0,15.99,Credit Card,East,109,0,4.0

In [22]:
# Dataset shape (rows, columns)
df.shape

(5000, 15)

In [23]:
# Column names and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   transaction_id   5000 non-null   int64
 1   order_date       5000 non-null   object
 2   customer_id      5000 non-null   int64
 3   product_id       5000 non-null   int64
 4   product_name     5000 non-null   object
 5   category         5000 non-null   object
 6   quantity         5000 non-null   int64
 7   unit_price       4900 non-null   float64
 8   discount_pct     4920 non-null   float64
 9   shipping_cost    5000 non-null   float64
 10  payment_method   5000 non-null   object
 11  region           5000 non-null   object
 12  store_id         5000 non-null   int64
 13  is_returned      5000 non-null   int64
 14  customer_rating  4768 non-null   float64
dtypes: float64(4), int64(6), object(5)
memory usage: 586.1+ KB

In [24]:
# Summary statistics
df.describe

<bound method NDFrame.describe of       transaction_id  order_date  customer_id  product_id product_name  \
0                  1  2023-04-13         1467          12       Laptop
1                  2  2024-03-11         1211           4        Mouse
2                  3  2023-12-15         1140          95       Webcam
3                  4  2023-09-28         1293          18       Tablet
4                  5  2023-04-17         1298          80     Keyboard
...              ...         ...          ...         ...          ...
4995            4996  2023-10-08         1221          77       Tablet
4996            4997  2023-04-04         1083          45        Mouse
4997            4998  2023-07-20         1182          88       Laptop
4998            4999  2023-01-21         1307          87      Charger
4999            5000  2023-12-06         1010          12     Keyboard

         category  quantity  unit_price  discount_pct  shipping_cost  \
0     Accessories         3      595.41           0.0           5.99
1     Accessories         6      754.54           5.0           5.99
2     Electronics         3      797.49          25.0           5.99
3       Computing         8     1040.93          25.0           5.99
4     Accessories         5     1069.70          15.0          15.99
...           ...       ...         ...           ...            ...
4995  Accessories         1      274.68          25.0           9.99
4996  Accessories         9      801.64          15.0           0.00
4997    Computing         9       74.95          25.0           0.00
4998  Electronics         6      753.78           0.0           9.99
4999  Accessories         7      196.93           5.0           9.99

     payment_method region  store_id  is_returned  customer_rating
0        Debit Card   West       106            1              4.0
1            PayPal  North       106            0              4.0
2            PayPal   West       104            0              5.0
3              Cash  South       105            0              5.0
4        Debit Card  North       103            0              5.0
...             ...    ...       ...          ...              ...
4995           Cash  North       110            0              3.0
4996           Cash   East       103            0              4.0
4997    Credit Card   East       105            0              5.0
4998    Credit Card  North       109            0              5.0
4999    Credit Card   East       110            0              5.0

[5000 rows x 15 columns]>

In [25]:
# Q2: Missing Values

# Count missing values in each column
df.isnull().sum()

transaction_id       0
order_date           0
customer_id          0
product_id           0
product_name         0
category             0
quantity             0
unit_price         100
discount_pct        80
shipping_cost        0
payment_method       0
region               0
store_id             0
is_returned          0
customer_rating    232
dtype: int64

In [26]:
# Calculate percentage of missing values
df.isnull().sum()/len(df) * 100

transaction_id     0.00
order_date         0.00
customer_id        0.00
product_id         0.00
product_name       0.00
category           0.00
quantity           0.00
unit_price         2.00
discount_pct       1.60
shipping_cost      0.00
payment_method     0.00
region             0.00
store_id           0.00
is_returned        0.00
customer_rating    4.64
dtype: float64

In [27]:
len(df)

5000

In [32]:
# Fill missing unit_price with median
df['unit_price'].fillna({'unit_price':df['unit_price'].median(),'inplace':True})

0        595.41
1        754.54
2        797.49
3       1040.93
4       1069.70
         ...
4995     274.68
4996     801.64
4997      74.95
4998     753.78
4999     196.93
Name: unit_price, Length: 5000, dtype: float64

In [37]:
# Fill missing discount_pct with 0
df['discount_pct'].fillna({'discount_pct':0,'inplace':True})

0        0.0
1        5.0
2       25.0
3       25.0
4       15.0
        ...
4995    25.0
4996    15.0
4997    25.0
4998     0.0
4999     5.0
Name: discount_pct, Length: 5000, dtype: float64

In [38]:
df.isnull().sum()

transaction_id       0
order_date           0
customer_id          0
product_id           0
product_name         0
category             0
quantity             0
unit_price           0
discount_pct         0
shipping_cost        0
payment_method       0
region               0
store_id             0
is_returned          0
customer_rating    232
dtype: int64

In [39]:
df.head(20)

,transaction_id,order_date,customer_id,product_id,product_name,category,quantity,unit_price,discount_pct,shipping_cost,payment_method,region,store_id,is_returned,customer_rating
0,1,2023-04-13,1467,12,Laptop,Accessories,3,595.410,0.0,5.99,Debit Card,West,106,1,4.0
1,2,2024-03-11,1211,4,Mouse,Accessories,6,754.540,5.0,5.99,PayPal,North,106,0,4.0
2,3,2023-12-15,1140,95,Webcam,Electronics,3,797.490,25.0,5.99,PayPal,West,104,0,5.0
3,4,2023-09-28,1293,18,Tablet,Computing,8,1040.930,25.0,5.99,Cash,South,105,0,5.0
4,5,2023-04-17,1298,80,Keyboard,Accessories,5,1069.700,15.0,15.99,Debit Card,North,103,0,5.0
5,6,2023-03-13,1401,36,Mouse,Accessories,4,572.670,10.0,5.99,Cash,East,103,0,5.0
6,7,2023-07-08,1101,25,Monitor,Electronics,9,626.180,20.0,15.99,Debit Card,South,109,0,4.0
7,8,2023-01-21,1304,87,Tablet,Electronics,5,566.810,15.0,0.00,Debit Card,West,105,0,4.0
8,9,2023-04-13,1359,76,Tablet,Electronics,4,809.440,0.0,9.99,Credit Card,North,101,0,4.0
9,10,2023-05-02,1028,98,Headphones,Electronics,8,685.500,20.0,15.99,Credit Card,East,109,0,4.0
10,11,2024-04-11,1041,36,Tablet,Accessories,8,1335.500,5.0,9.99,PayPal,West,110,0,5.0
11,12,2023-08-03,1355,67,Webcam,Computing,8,1047.580,15.0,9.99,Debit Card,South,106,0,5.0
12,13,2023-11-27,1303,9,Headphones,Computing,4,777.445,20.0,9.99,PayPal,East,109,0,4.0
13,14,2024-04-03,1496,61,Mouse,Electronics,1,1066.610,15.0,15.99,Cash,South,107,0,5.0
14,15,2023-03-29,1146,53,Monitor,Electronics,2,1456.780,5.0,15.99,PayPal,North,110,0,4.0
15,16,2024-01-08,1256,18,Monitor,Accessories,4,957.250,25.0,15.99,Cash,East,110,0,3.0
16,17,2023-04-10,1462,43,Charger,Electronics,10,1445.690,15.0,0.00,Credit Card,North,107,0,4.0
17,18,2023-12-26,1227,35,Charger,Computing,2,245.670,0.0,15.99,Credit Card,West,105,0,5.0
18,19,2023-06-01,1236,63,Mouse,Electronics,10,88.190,20.0,0.00,Cash,West,107,1,4.0
19,20,2023-05-11,1361,98,Speaker,Computing,3,872.900,20.0,15.99,Cash,South,110,0,5.0

In [43]:
# Fill missing customer_rating with mode
df['customer_rating'] = df['customer_rating'].fillna(df['customer_rating'].mode()[0])

In [44]:
df.isnull().sum()

transaction_id     0
order_date         0
customer_id        0
product_id         0
product_name       0
category           0
quantity           0
unit_price         0
discount_pct       0
shipping_cost      0
payment_method     0
region             0
store_id           0
is_returned        0
customer_rating    0
dtype: int64

In [45]:
# Q3: Basic Calculations
# Create new columns:

# revenue = quantity × unit_price
df['revenue']=df['quantity']*df['unit_price']

In [46]:
# discount_amount = revenue × (discount_pct / 100)
df['discount_amount']=df['revenue']*(df['discount_pct']/100)

In [47]:
# net_revenue = revenue - discount_amount
df['net_revenue']=df['revenue']-df['discount_amount']

In [48]:
# total_cost = net_revenue + shipping_cost
df['total_cost']=df['net_revenue']+df['shipping_cost']

In [49]:
df.columns

Index(['transaction_id', 'order_date', 'customer_id', 'product_id',
       'product_name', 'category', 'quantity', 'unit_price', 'discount_pct',
       'shipping_cost', 'payment_method', 'region', 'store_id', 'is_returned',
       'customer_rating', 'revenue', 'discount_amount', 'net_revenue',
       'total_cost'],
      dtype='object')

In [50]:
df.head(3)

,transaction_id,order_date,customer_id,product_id,product_name,category,quantity,unit_price,discount_pct,shipping_cost,payment_method,region,store_id,is_returned,customer_rating,revenue,discount_amount,net_revenue,total_cost
0,1,2023-04-13,1467,12,Laptop,Accessories,3,595.41,0.0,5.99,Debit Card,West,106,1,4.0,1786.23,0.0000,1786.2300,1792.2200
1,2,2024-03-11,1211,4,Mouse,Accessories,6,754.54,5.0,5.99,PayPal,North,106,0,4.0,4527.24,226.3620,4300.8780,4306.8680
2,3,2023-12-15,1140,95,Webcam,Electronics,3,797.49,25.0,5.99,PayPal,West,104,0,5.0,2392.47,598.1175,1794.3525,1800.3425

In [51]:
df.describe()

,transaction_id,customer_id,product_id,quantity,unit_price,discount_pct,shipping_cost,store_id,is_returned,customer_rating,revenue,discount_amount,net_revenue,total_cost
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,1249.990400,51.184400,5.446000,770.055706,12.470000,8.064846,105.514600,0.084000,4.274400,4241.691049,531.806367,3709.884682,3717.949528
std,1443.520003,144.034687,28.767814,2.862014,425.737008,8.598482,5.826669,2.862696,0.277416,0.908884,3498.571346,645.192217,3099.713499,3099.788408
min,1.000000,1001.000000,1.000000,1.000000,10.070000,0.000000,0.000000,101.000000,0.000000,1.000000,13.100000,0.000000,11.722500,11.790000
25%,1250.750000,1124.750000,26.000000,3.000000,413.640000,5.000000,5.990000,103.000000,0.000000,4.000000,1357.897500,56.364750,1177.260500,1187.082000
50%,2500.500000,1248.000000,52.000000,5.000000,777.445000,10.000000,9.990000,106.000000,0.000000,4.000000,3288.045000,288.077500,2860.991250,2867.907000
75%,3750.250000,1376.000000,76.000000,8.000000,1130.997500,20.000000,15.990000,108.000000,0.000000,5.000000,6278.790000,766.890625,5516.688500,5526.730625
max,5000.000000,1500.000000,100.000000,10.000000,1499.850000,25.000000,15.990000,110.000000,1.000000,5.000000,14942.700000,3672.650000,14861.800000,14877.790000